// ============================================
// PLAYER PROFILE SYSTEM
// The "Character Sheet" for your productivity RPG
// ============================================

class PlayerProfile {
    constructor(playerSystem) {
        this.playerSystem = playerSystem;
        this.isVisible = false;
        this.modal = null;
        this.init();
    }

    init() {
        this.injectModal();
        this.attachListeners();
        console.log('👤 Player Profile UI initialized');
    }

    injectModal() {
        const modalHtml = `
            <div id="profileModal" class="profile-modal" style="display: none;">
                <div class="profile-backdrop"></div>
                <div class="profile-content glass-card">
                    <button class="close-profile">×</button>
                    
                    <div class="profile-header">
                        <div class="rank-badge-large" id="profileRankBadge">
                            <div class="rank-letter" id="profileRankLetter">E</div>
                            <div class="rank-title" id="profileRankTitle">Novice Player</div>
                        </div>
                        <div class="level-info">
                            <div class="level-number">LEVEL <span id="profileLevel">1</span></div>
                            <div class="xp-bar-container">
                                <div class="xp-bar-fill" id="profileXPFill"></div>
                                <div class="xp-text" id="profileXPText">0 / 100 XP</div>
                            </div>
                        </div>
                    </div>

                    <div class="profile-grid">
                        <!-- Stats Section -->
                        <div class="profile-section stats-section">
                            <h3>📊 PLAYER STATS</h3>
                            <div class="stats-visual">
                                <!-- Hexagon Canvas -->
                                <canvas id="statsHexagon" width="200" height="200"></canvas>
                            </div>
                            <div class="stats-list" id="profileStatsList">
                                <!-- Generated by JS -->
                            </div>
                        </div>

                        <!-- Achievements Section -->
                        <div class="profile-section achievements-section">
                            <h3>🏆 ACHIEVEMENTS</h3>
                            <div class="achievements-grid" id="profileAchievements">
                                <!-- Generated by JS -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `;

        document.body.insertAdjacentHTML('beforeend', modalHtml);
        this.modal = document.getElementById('profileModal');
    }

    attachListeners() {
        // Close button
        this.modal.querySelector('.close-profile').addEventListener('click', () => this.close());
        this.modal.querySelector('.profile-backdrop').addEventListener('click', () => this.close());

        // Attach click to header items (Rank/Level)
        // We wait a bit for DOM to be fully ready or just attach securely
        setTimeout(() => {
            const aiStatus = document.getElementById('aiStatus');
            const aiBadge = document.querySelector('.ai-badge');

            if (aiStatus) aiStatus.style.cursor = 'pointer';
            if (aiBadge) aiBadge.style.cursor = 'pointer';

            if (aiStatus) aiStatus.addEventListener('click', () => this.open());
            if (aiBadge) aiBadge.addEventListener('click', () => this.open());
        }, 1000);

        // Keyboard shortcut: P
        document.addEventListener('keydown', (e) => {
            if (e.key === 'p' && !e.ctrlKey && !e.metaKey && document.activeElement.tagName !== 'INPUT') {
                this.open();
            }
        });
    }

    open() {
        if (!this.playerSystem) return;

        this.isVisible = true;
        this.modal.style.display = 'flex';
        this.updateData();

        // Slight animation delay for canvas
        setTimeout(() => this.drawHexagon(), 100);
    }

    close() {
        this.isVisible = false;
        this.modal.style.display = 'none';
    }

    updateData() {
        const player = this.playerSystem.dm.data.player;
        const xpRequired = this.playerSystem.getXPRequired(player.level);

        // Header
        document.getElementById('profileRankLetter').textContent = player.rank;
        document.getElementById('profileRankTitle').textContent = player.title;
        document.getElementById('profileLevel').textContent = player.level;
        document.getElementById('profileXPText').textContent = `${player.xp} / ${xpRequired} XP`;

        const xpPercent = (player.xp / xpRequired) * 100;
        document.getElementById('profileXPFill').style.width = `${xpPercent}%`;

        // Stats List
        const statsList = document.getElementById('profileStatsList');
        statsList.innerHTML = Object.entries(player.stats).map(([key, value]) => `
            <div class="stat-row">
                <span class="stat-name">${key.toUpperCase()}</span>
                <span class="stat-val ${this.getStatClass(value)}">${value}</span>
            </div>
        `).join('');

        // Achievements
        const achievementsGrid = document.getElementById('profileAchievements');
        // Define all achievements with icons (we can pull from PlayerSystem if structured or hardcode here for visuals)
        const allAchievements = [
            { id: 'first_quest', icon: '⚔️', name: 'First Steps' },
            { id: 'level_5', icon: '🔥', name: 'Rising Power' },
            { id: 'level_10', icon: '⚡', name: 'Double Digits' },
            { id: 'd_rank', icon: '🦅', name: 'Awakened' },
            { id: 'c_rank', icon: '🐅', name: 'Warrior' },
            { id: 'b_rank', icon: '🥋', name: 'Master' },
            { id: 'a_rank', icon: '👑', name: 'Elite' },
            { id: 's_rank', icon: '☠️', name: 'Monarch' },
            { id: 'streak_7', icon: '📅', name: 'Week Warrior' },
            { id: 'streak_30', icon: '🗓️', name: 'Month Master' },
            { id: 'discipline_50', icon: '🛡️', name: 'Iron Will' },
            { id: 'discipline_100', icon: '💎', name: 'Unbreakable' }
        ];

        achievementsGrid.innerHTML = allAchievements.map(ach => {
            const unlocked = player.achievements.includes(ach.id);
            return `
                <div class="achievement-badge ${unlocked ? 'unlocked' : 'locked'}" title="${ach.name}">
                    <div class="ach-icon">${ach.icon}</div>
                    ${unlocked ? '<div class="ach-check">✓</div>' : ''}
                </div>
            `;
        }).join('');

        // Update styling based on rank
        const rankColors = {
            E: '#999', D: '#4a9eff', C: '#00ff87', B: '#ff00f5', A: '#ffaa00', S: '#ffd700'
        };
        const color = rankColors[player.rank] || '#fff';
        document.getElementById('profileRankLetter').style.color = color;
        document.getElementById('profileRankBadge').style.borderColor = color;
        document.getElementById('profileXPFill').style.background = color;
    }

    drawHexagon() {
        const canvas = document.getElementById('statsHexagon');
        if (!canvas) return;
        const ctx = canvas.getContext('2d');
        const w = canvas.width;
        const h = canvas.height;
        const cx = w / 2;
        const cy = h / 2;
        const r = w / 2 - 20;

        const player = this.playerSystem.dm.data.player;
        const stats = player.stats;

        // Normalize stats (assume max 100)
        const data = [
            stats.focus,      // Top
            stats.discipline, // Right
            stats.consistency,// Bottom
            stats.energy,     // Left
            (stats.focus + stats.discipline) / 2, // Filler for 5th point if pentagon?
            (stats.consistency + stats.energy) / 2
        ];

        // Wait, we have 4 stats. Let's make it a Diamond/Square rotated.
        // Or mapped to 4 points.

        ctx.clearRect(0, 0, w, h);

        // Draw background grid
        ctx.strokeStyle = 'rgba(255, 255, 255, 0.1)';
        ctx.lineWidth = 1;
        for (let i = 1; i <= 3; i++) {
            this.drawPoly(ctx, cx, cy, r * (i / 3), 4, 0); // 0 rotation
        }

        // Draw labels
        ctx.fillStyle = 'rgba(255, 255, 255, 0.6)';
        ctx.font = '10px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('FOCUS', cx, cy - r - 5);
        ctx.fillText('DISC.', cx + r + 15, cy + 3);
        ctx.fillText('CONST.', cx, cy + r + 15);
        ctx.fillText('ENERGY', cx - r - 20, cy + 3);

        // Draw Player Stats
        const values = [
            stats.focus / 100,
            stats.discipline / 100,
            stats.consistency / 100,
            stats.energy / 100
        ];

        ctx.beginPath();
        values.forEach((val, i) => {
            const angle = (Math.PI * 2 * i) / 4 - Math.PI / 2;
            const x = cx + Math.cos(angle) * (r * val);
            const y = cy + Math.sin(angle) * (r * val);
            if (i === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        });
        ctx.closePath();

        ctx.fillStyle = 'rgba(0, 245, 255, 0.4)';
        ctx.fill();
        ctx.strokeStyle = '#00f5ff';
        ctx.lineWidth = 2;
        ctx.stroke();
    }

    drawPoly(ctx, cx, cy, r, sides, rotation) {
        ctx.beginPath();
        for (let i = 0; i < sides; i++) {
            const angle = (Math.PI * 2 * i) / sides - Math.PI / 2 + rotation;
            const x = cx + Math.cos(angle) * r;
            const y = cy + Math.sin(angle) * r;
            if (i === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.closePath();
        ctx.stroke();
    }

    getStatClass(val) {
        if (val >= 80) return 's-tier';
        if (val >= 60) return 'a-tier';
        if (val >= 40) return 'b-tier';
        return 'c-tier';
    }
}

// Global instance
window.PlayerProfile = PlayerProfile;

// Auto-init logic if PlayerSystem exists
document.addEventListener('DOMContentLoaded', () => {
    // Wait for PlayerSystem to be available
    /* 
       Initialized in player-integration.js usually.
       We can init this profile in index.html after scripts load
       or hook into existing init flows.
       Let's attach it to window.
    */
    setTimeout(() => {
        if (window.playerSystem) {
            window.playerProfile = new PlayerProfile(window.playerSystem);
        }
    }, 500);
});
